Chromium style clang fixes for OVERRIDE in compositor_unittests
Fixes clang plugin complaint about missing override:
./ui/gfx/compositor/compositor_cc.h:35:11: error: [chromium-style] Overriding method must be marked with OVERRIDE.
  virtual void* GetDisplay();
          ^
Also, adds |SetCurrent| call to properly track context in |GLContextNSView::MakeCurrent|.

BUG=104390
TEST=Compiles on Mac/clang.  compositor_unittests pass.
R=piman@chromium.org, kbr@chromium.org

Review URL: http://codereview.chromium.org/8748018

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@112291 0039d316-1c4b-4281-b951-d872f2087c98

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: a803592b764704068582548d7cf9a7f8ce55a017