Revert 156200 - Conservative update button/label/textfield content
[ RUN      ] NativeTextfieldViewsTest.ModelChangesTestLowerCaseWithLocale
controls\textfield\native_textfield_views_unittest.cc(434): error: Value of:
model_->GetText()
  Actual: L"\x131"
  Expected: WideToUTF16(L"i")
  Which is: L"i"
  [  FAILED  ] NativeTextfieldViewsTest.ModelChangesTestLowerCaseWithLocale (16
  ms)

If I had to guess it's that i is considered the same as ı somehow.

Saves a repaint when no change actually occurs.

BUG=chrome-os-partner:13141
TEST=build, run on lumpy, lucas

Change-Id: I6ccb75141b7639571e24b2fbf7e3986d85e98cbc

Review URL: https://chromiumcodereview.appspot.com/10916222

TBR=sheu@chromium.org
Review URL: https://chromiumcodereview.appspot.com/10916254

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@156206 0039d316-1c4b-4281-b951-d872f2087c98

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: b482fe747ceeb396730cd5ca048feff98f2b770c