oak: Fix component build.
The first patch that tried to convert oak from static_library to component was
r136217, but later it was reverted in r136229 because it broke the aura
compile on Linux and Windows with the following error:

out/Release/../../third_party/gold/gold64:
out/Release/obj.target/ash/libash.so:error: undefined reference to
'oak::ShowOakWindow()'to...

The only change here from the first patch was the addition of oak.h include in
oak_window.cc, and that addition seems to have fixed the above issue.

I'll make sure it passes linux_aura,win_aura before landing this again.

TEST=run out/Debug/ash_shell --ash-enable-oak, press Ctrl+Shift+F1, the Oak
window should appear and it should work fine.
R=ben@chromium.org

Review URL: https://chromiumcodereview.appspot.com/10453007

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@139036 0039d316-1c4b-4281-b951-d872f2087c98

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: a6709eb3616e9af71a12a4eb436e2a55358b6386