Broke the aura compile on Linux and Windows.
out/Release/../../third_party/gold/gold64:
out/Release/obj.target/ash/libash.so:error: undefined reference to
'oak::ShowOakWindow()'

Revert 136217 - ui/oak: Build oak as a component library.

And export ShowOakWindow() function.

R=ben@chromium.org

Review URL: https://chromiumcodereview.appspot.com/10310050

TBR=tfarina@chromium.org
Review URL: https://chromiumcodereview.appspot.com/10389058

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@136229 0039d316-1c4b-4281-b951-d872f2087c98

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: e17fd74ae492c7ef1e1388d9a2ea6a061e33f8ac